version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/   

hooks:
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 180
      runas: ubuntu
#  ValidateService:
#    - location: scripts/apphealth.sh
#      timeout: 180
#      runas: ubuntu