version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/

hooks:
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/apphealth.sh
      timeout: 180
      runas: root